import Head from 'next/head'
import {PrismaClient} from '@prisma/client';
import {Game} from '../../models/Game';
import {Context} from 'vm';
import HeaderComponent from '../../components/HeaderComponent';
import FooterComponent from '../../components/FooterComponent';

const prisma = new PrismaClient();
export async function getServerSideProps(context: Context) {
  const id: number = parseInt(context.params.id);

  const game = await prisma.game.findUnique({
    where: { id }
  });
  return {props: { game }}
}

type Props = { game: Game };
export default function GameInfo(props: Props) {
  const { game } = props;

  return (
      <div>
        <Head>
          <title>GameLib | Accueil</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className={'container mx-auto'}>
          <HeaderComponent/>
          <img src={game.thumbnail} alt={`${game.title} thumbnail`}/>
        </div>

        <FooterComponent/>
      </div>
  )
}
