import Head from 'next/head'
import Header from '../../components/HeaderComponent';
import FooterComponent from '../../components/FooterComponent';
import HeaderComponent from '../../components/HeaderComponent';

export default function Index() {
  return (
      <div>
        <Head>
          <title>GameLib | Liste</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className={'container mx-auto'}>
          <HeaderComponent/>
          Game
        </div>

        <FooterComponent/>
      </div>
  )
}
