import Head from 'next/head';
import NavBar from '../components/NavBarComponent';
import Header from '../components/HeaderComponent';
import HeaderComponent from '../components/HeaderComponent';
import FooterComponent from '../components/FooterComponent';

export default function Contact() {
  return (
      <div>
        <Head>
          <title>GameLib | Contact</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className={'container mx-auto'}>
          <HeaderComponent/>
          Contact
        </div>

        <FooterComponent/>
      </div>
  )
}